### ISSUE TITLE
bundle.js:36248 Cannot handle data of type:application/octet-stream

### ISSUE THREAD

**Issue by metanerd** [Qafoo/QualityAnalyzer#222]
Tried to serve the application after analyzing src/php folder of QualityAnalyzer. There are also issues with bundle.js.map and bundle.css.map. I am running it inside a vagrant machine. I could access the site, 'Initializing application' is check marked. Then the title error is thrown during loading data of the project.json file.

**Comment by Gladhon** [comment]
same here

**Comment by Maxlab** [comment]
all the same

**Comment by Maxlab** [comment]
solved for my checkout on greenkeeper-babel-core-6.3.13 version

**Comment by kore** [comment]
Looks like I forgot to recompile the bundled JS files. I hope it is resolved now – please re-open if the issue persists please post a reproducing example on public code.

At least it works for me when running:

```bash
~/d/Q/qa (master) $ analyze analyze src/
Analyze source code in /home/kore/devel/Qafoo/qa/src
 * Running source
 * Running coverage
 * Running pdepend
 * Running dependencies
 * Running phpmd
 * Running checkstyle
 * Running tests
 * Running cpd
 * Running phploc
 * Running git
 * Running gitDetailed
Done
~/d/Q/qa (master) $ analyze serve
Starting webserver on http://localhost:8080/
```
