### ISSUE TITLE
Composer global install

### ISSUE THREAD

**Issue by theofidry** [Qafoo/QualityAnalyzer#4]
Wouldn't it be possible to make it installable via Composer?

**Comment by theofidry** [comment]
Being resolved by #5

**Comment by ct-jensschulze** [comment]
Did you tried if it would work? I just wanted to have a test run in my project.

**Comment by theofidry** [comment]
the composer package is not published

**Comment by ct-jensschulze** [comment]
Add to your ~/.composer/config.json:

```
{
...
 	"repositories": [
	  {
	    "type": "vcs",
	    "url": "https://github.com/ct-jensschulze/QualityAnalyzer"
	  }
	]
}

Then you can run:
```
composer global require qafoo/quality-analyzer:dev-master
```

And execute the analyzer like this:
```
~/.composer/vendor/bin/analyze analyze src/
```

**Comment by theofidry** [comment]
No I haven't tried this way. I mean if you want to use it via Composer a composer package should be published this solution is just a workaround.

**Comment by ct-jensschulze** [comment]
Yes. Was just meant as help for testing. And i totally agree it should be published with packagist, but before it should be able to run the analyzer standalone as well as located in the vendor/bin folder. And when I cannot publish the package as the namespace is already reserved (also it would not be very nice to do this ;-)) But at least with the PR it's now possible and works for standalone and as a composer package.

**Comment by kore** [comment]
Fixed by https://github.com/Qafoo/QualityAnalyzer/pull/5

**Comment by theofidry** [comment]
It is not @kore. #5 ensure that you can install this tool globally via composer, but you still have to give the vcs repository. A Composer package `qafoo/quality-analyzer` would be welcomed.

**Comment by kore** [comment]
You are right. Will take care of that.

**Comment by kore** [comment]
https://packagist.org/packages/qafoo/quality-analyzer … sorry it took a little longer – access permissions on packagist.org.

**Comment by theofidry** [comment]
Thanks!
