### ISSUE TITLE
Exclude files/folder from scanning

### ISSUE THREAD

**Issue by Mte90** [Qafoo/QualityAnalyzer#65]
I use some libraries from others but I don't want to scan them for speed up the process and not have to study also their code.
There is a way to do that?

**Comment by kore** [comment]
As mentioned here: https://github.com/Qafoo/QualityAnalyzer#usage and in ``--help`` there is the ``--exclude`` CLI option to do that.

**Comment by Mte90** [comment]
thank you, I have read the readme but I have missed that!

**Comment by Mte90** [comment]
In the xml examples is not specified how to insert the files to exclude.
I have to do that for every tool?

**Comment by kore** [comment]
Yeah, and they sadly behave differently in that regard. It is just an example to get you started.

As far as I can see it there is no sane way for the analyzer itself to support all the diffrent options.
